name: 'CI'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  rollup-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Rollup check
        run: rollup -c

  typescript-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Install typescript
        run: npm install --global typescript
      - name: TypeScript check
        run: tsc --noEmit

  jest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Jest check
        run: npm run test